version: 2
project_name: trafficmirror
release:
  github:
    owner: rb3ckers
    name: trafficmirror
  name_template: '{{.Tag}}'
before:
  hooks:
  - go mod tidy
  - go mod download
builds:
- env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  ldflags:
    - -s -w -X github.com/rb3ckers/trafficmirror.Version={{.Version}}
    - -X github.com/rb3ckers/trafficmirror.Commit={{.Commit}}
    - -X github.com/rb3ckers/trafficmirror.Date={{.Date}}
checksum:
  name_template: checksums.txt
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - "^docs:"
    - "^test:"
dockers:
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    image_templates:
      - "{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:latest"
      - "{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:latest"
      - "{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:{{ .Tag }}"
      - "{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Major }}"
      - "{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Major }}.{{ .Minor }}"
